# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = 'Bio'
  pageRef = '/'
  weight = 9

[[main]]
  name = 'Educazione'
  pageRef = '/education'
  weight = 10

[[main]]
  name = 'Esperienze'
  pageRef = '/experiences'
  weight = 11

[[main]]
  name = 'Competenze'
  pageRef = '/skills'
  weight = 12

[[main]]
  name = 'Progetti'
  pageRef = '/portfolio'
  weight = 13

[[main]]
  name = 'Blog'
  pageRef = '/blog'
  weight = 14


[[main]]
  identifier = 'search'
  weight = 99
  [main.params]
    action = 'search'

[[main]]
  identifier = 'locale'
  weight = 100
  [main.params]
    action = 'locale'

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#   name = 'Tags'
#   pageRef = 'tags'
#   weight = 10


[[footer]]
  name = 'Bio'
  pageRef = '/'
  weight = 9

[[footer]]
  name = 'Edu'
  pageRef ='/education'
  weight = 10

[[footer]]
  name = 'Esperienze'
  pageRef = '/experiences'
  weight = 11

[[footer]]
  name = 'Competenze'
  pageRef = '/skills'
  weight = 12

[[footer]]
  name = 'Progetti'
  pageRef = '/portfolio'
  weight = 13

[[footer]]
  name = 'Blog'
  pageRef = '/posts'
  weight = 14